### ISSUE TITLE
.NET 5 and Blazor Server Application Combination is not working in IE11

### ISSUE THREAD

**Issue by jesusarockias** [Daddoon/Blazor.Polyfill#32]
.NET SDK - 5.0.100-preview.7.20366.6

Visual Studio - 16.7.0 Preview 5.0 

We can reproduce it with default counter component by clicking it count value will not be updated.

**Comment by Daddoon** [comment]
I don't have time to look at this issue at the moment.

- Does this fail with the default Blazor template ?
- Can you see if there is any error throwing in the console ? If yes post it here.

Theses kind of issues or often related to Blazor Server using some new Javascript API internally with it's .js file, not available on IE11.

In theses cases, the fix is often to add the missing polyfill to the package.

**Comment by jesusarockias** [comment]
@Daddoon For your information, 
1. Server Side Blazor application
2. It is working completely fine in IE11 while created with .netcore 3.1

**Comment by Daddoon** [comment]
Good to know. 

Still, do you have any error in the console ?

**Comment by jesusarockias** [comment]
Sorry. I am not able to open the development tool since IE browser stopped working. So, I have attached the sample here.

**Comment by Daddoon** [comment]
There is no bug, you are not using the latest version (3.0.8) , but 3.0.1 in your simple.
Update to the latest version, it works.

**Comment by Daddoon** [comment]
An update has been shipped for .NET 5.0 Blazor server-side support.
Of course since the last time, support for IE11 on .NET 5.0 has been added, some days ago too.

In case you are interested:

- Nuget page: https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.100.1
- Some additional informations on the updated doc: https://github.com/Daddoon/Blazor.Polyfill
- Release page here: https://github.com/Daddoon/Blazor.Polyfill/releases/tag/5.0.100.1

> - Add **Edge Legacy** (EdgeHTML engine) support
> - Fix missing reconnection modal behavior on **Internet Explorer 11** and **Edge Legacy**
> - Add pre-caching of all files needed for this library at the first web app request, in order to prevent further requests to wait for file generation on the server before serving the app. This mean that, now, if the app page is shown, then everything is ready.
