### ISSUE TITLE
.NET 5 RC1 requires dynamic import polyfill.

### ISSUE THREAD

**Issue by StevenGranados** [Daddoon/Blazor.Polyfill#33]
I get the error 
![image](https://user-images.githubusercontent.com/51818199/94034916-706a9900-fdba-11ea-8d54-4713929f8329.png)
when running the default project in .NET 5 RC1.
This is the line:
![image](https://user-images.githubusercontent.com/51818199/94035038-8f692b00-fdba-11ea-8c34-b667727522d3.png)
The error occurs at the import(e) function.
I think this is caused by the new JSObjectReference feature.

Update: 
I have a workaround.
If you add these lines into the top of _Host.cshtml
'''
@using System.IO
@using System.Reflection
'''
And these to the top of the body of _Host.cshtml:
```
@{
        var assembly = Assembly.Load("Microsoft.AspNetCore.Components.Server");
        var resources = assembly.GetManifestResourceNames();
        var resourceName = resources .Single(str => str.EndsWith("blazor.server.js"));

        using (Stream stream = assembly.GetManifestResourceStream(resourceName))
        using (StreamReader reader = new StreamReader(stream))
        {
            string js = reader.ReadToEnd();
            js = js.Remove(67710, 140);
            js = js.Replace(@"/\W*Blazor:[^{]*(?<descriptor>.*)$/", @"/\W*Blazor:[^{]*(.*)$/");
            js = js.Replace(@"r.groups&&r.groups.descriptor", @"r[1]");
            System.IO.File.WriteAllText(System.IO.Path.Combine("wwwroot", "js", "blazor.server.js"), js);
        }
}
```
Then change the line
`<script src="_framework/blazor.server.js"></script>`
to
`<script src="js/blazor.server.js"></script>`
This gets the file from the assembly, edits it to remove the offending line, changes a regex group name to indexed groups and saves it locally.
Is this something that can be put into the library?

**Comment by kmuthukumar23** [comment]
Hi Team,

I have also faced the same issue in RC 5.0 with IE11

**Comment by Daddoon** [comment]
@StevenGranados Thanks for having digged into the issue.

I see that you are fixing the issue by rewriting some content of **blazor.server.js** .

As i'm not actually looking into the code, what is your regex actually searching and changing ? I mean, what thing in the Blazor library does crash the polifill now ?

Thanks !

**Comment by Daddoon** [comment]
Oops, just seen your text about JSObjectReference.

I will try to take a look at this in few days.

**Comment by StevenGranados** [comment]
Yeah I removed the import function which (I think) is related to JSObjectReference. This will break JSObjectReference.
I also replaced the group name regex, which is unrelated.

**Comment by Daddoon** [comment]
Will work on this very soon.

**Comment by benm-eras** [comment]
@Daddoon I realise I am not in a position to demand or even pester you regarding this issue, but I was wondering if there has been any progress? 

Do you think it is likely that you will be able to provide a functioning polyfill for Blazor **server** in IE11? 

I am really not keen on editing the framework provided script files to remove a call when I am not 100% sure what it is doing...

Thanks for all your work!

**Comment by Daddoon** [comment]
I was overwhelmed by work this month, and didn't had the time to take a break about that, and maybe also i have missed that i wanted to fix this issue by the time.

I will try to make a first look tomorrow, see if there is any "fast" fix possibe to add into the library.

**Comment by benm-eras** [comment]
I completely understand, and really appreciate the response. 

I have tried editing the `blazor.server.js` file, changing that call to `import(e)` to a call to my own stub function that does nothing but output to the console. IE11 then promptly trips up on the declaration of a RegExp later in the script, I think because it uses the literal notation, but I swapped that out for a `new RegExp(...)` only for it to throw an error related to regular expressions (`Unexpected quantifier`) later on in part of `core-js` which I think is included as part of your polyfill?

Anyway, I am not sure where to go from here. I don't have the luxury of dropping support for IE11 sadly...

**Comment by StevenGranados** [comment]
That's what these lines in my post do:
```
js = js.Replace(@"/\W*Blazor:[^{]*(?<descriptor>.*)$/", @"/\W*Blazor:[^{]*(.*)$/");
js = js.Replace(@"r.groups&&r.groups.descriptor", @"r[1]");
```
They remove the offending named regex groups and replace it with numbered regex groups.

Oddly enough it's the only place they're used, and numbered regex is used elsewhere. Maybe Microsoft have made the decision to start writing the JavaScript beyond ES5 for Blazor, and more lines will have to be manually changed in the future...
Maybe a transpiler is needed as well as a polyfill.

**Comment by Daddoon** [comment]
So far, i will not ship an update today as i don't have found some bits that i would like in order to be able to ship a good update.

My investigation so far, very close to what @StevenGranados seen:

- First, i needed to transpile through Babel **Blazor.server.js**, with the "ie 11" profile. It fixed some impossible requirements like the **import** statement, and surely fixed some other ambiguous things. Even if i cannot ship a fix directly from Blazor.polyfill.js, we can surely create a NuGet package that would on the fly create a transpiled **Blazor.server.js** from the current executing runtime of Blazor, and return this cached transpiled version when we detect in the User-Agent of the request that the browser is IE11 (Trident etc.).
- But even with this good transpilation, one thing does not go right out of the box. As stated by @StevenGranados , we should replace:

```js
 i = r && r.groups && r.groups.descriptor;
```
By
```js
i = r && r[1];
```

In the script (Line 6893 from my modified versions), as we must reflect the "capturing" behavior of this part to the fact that transpiling "simplified" the previous regexp as IE11 does not have capturing group.

Or at least find a polyfill that fix that issue and tell Babel to not simplify this on the other hand, but still have to search about it.

**Comment by Daddoon** [comment]
> 
> 
> That's what these lines in my post do:
> 
> ```
> js = js.Replace(@"/\W*Blazor:[^{]*(?<descriptor>.*)$/", @"/\W*Blazor:[^{]*(.*)$/");
> js = js.Replace(@"r.groups&&r.groups.descriptor", @"r[1]");
> ```
> 
> They remove the offending named regex groups and replace it with numbered regex groups.
> 
> Oddly enough it's the only place they're used, and numbered regex is used elsewhere. Maybe Microsoft have made the decision to start writing the JavaScript beyond ES5 for Blazor, and more lines will have to be manually changed in the future...
> Maybe a transpiler is needed as well as a polyfill.

Woopsies, our replies just crossed at the same time !

**Comment by StevenGranados** [comment]
What are the chances :). I'm glad to hear that it seems do-able! 
Do you mean to say that the import statement is impossible to transpile with Babel and it's removing it or is Babel able to work some magic?

**Comment by Daddoon** [comment]
It seem to do some magics, but i have no clue what exactly. I mean i don't have debbuged step by step.
It look like this instead:

```js
    i[0]._cachedFunctions.set("import", function (e) {
      return "string" == typeof e && e.startsWith("./") && (e = document.baseURI + e.substr(2)), Promise.resolve("".concat(e)).then(function (s) {
        return _interopRequireWildcard(require(s));
      });
    });
```
And the method call:

```js
function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } if (obj === null || _typeof(obj) !== "object" && typeof obj !== "function") { return { default: obj }; } var cache = _getRequireWildcardCache(); if (cache && cache.has(obj)) { return cache.get(obj); } var newObj = {}; var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null; if (desc && (desc.get || desc.set)) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } newObj.default = obj; if (cache) { cache.set(obj, newObj); } return newObj; }
```

No clue on how it impact the experience, but at least the default template was still working with this code, out of the box.

**Comment by Daddoon** [comment]
Just a note for me, it seem that the current generated wrapper for Regex in the transpiled code by babel is only working for ES6, but IE11 is ES5.

https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex

I will try in few days to transpile with the "runtime" option to false in this babel plugin, in order to keep regexp in the old format, and try to see if an other polyfill can cover the missing named group feature on IE11 instead.

**Comment by Daddoon** [comment]
I opened an issue on ASPNET Core repo, to see if they want to take a decision about the Regexp issue in a near future.

**Comment by Daddoon** [comment]
I think i will try to implement a fix next Monday, as i will have some time and my full work environment. I will try to do something similar to what you done @StevenGranados , except i will try to catch this at the HTTP level of the webserver in order to modify the required things.

This in order to not have to copy the library file (catching it instead) manually, and not having to alter the "_framework/blazor.server.js" line from the Web app. This way, this will be unrelated to copy specific content, and if blazor.server.js update in the future, even if we have to update the polyfill, you will not have to maintain this file by yourself directly.

In the end i would prefer that Microsoft change their RegExp usage, but we may see this in the future only.

**Comment by Daddoon** [comment]
Working on it, please be patient. If everything goes right, maybe an update during the week.

**Comment by Daddoon** [comment]
Just an update to say that Microsoft doesn't plan to support IE11 for .NET 5.0, see the reply in https://github.com/dotnet/aspnetcore/issues/28187 .

I will ship something sure, but we must keep in mind that things may stop working in the future depending the blazor.server.js evolution.

**Comment by benm-eras** [comment]
Thanks @Daddoon, I wish my users would fall in line and stop using IE11!

**Comment by Daddoon** [comment]
Things are nearly done !

I have a working class library for the ASP.NET Core Server that alter and fix the returned **blazor.server.js** file **only** if IE11 is detected in the calling request.

I still need to:

- [ ] Determine and simulate an ETag behavior for the **blazor.server.js for IE11** specific request handling in order to cache the file efficiently like a regular file for the browser. Also, if an future update come for any reason, being sure that the file will be updated accordingly.

At the moment, the file is cached on server-side, but not on the browser side, so it's not the perfect scenario as it force the server to send the file entirely at each site access. Not so great !

- [ ] Create a Nuget package for the Class Library

I will probably ship the fix tomorrow.

**Comment by Daddoon** [comment]
Done !

Please read the updated documentation !
Also if you can validate that the package work, it would be great.

Thanks !

And special thanks to @StevenGranados for pointing the starting point for the fix.

**Comment by StevenGranados** [comment]
Linking these two for reference. 
https://github.com/dotnet/aspnetcore/pull/26132
https://github.com/dotnet/aspnetcore/issues/26475

**Comment by Daddoon** [comment]
Well it's very specific.

I think there is two area of work for this:

- Edge Legacy on WASM
- Edge Legacy on Server-side

To be honest, i'm pretty sure that "forcing" the IE11 polyfill on Edge Legacy for Server-side will probably work out of the box, even if Edge Legacy doesn't need as many Polyfills and don't have theses ES5 issue.

However, i cannot guarantee anything about the Blazor WASM area on Legacy Edge. It's more complicated to know atm what would not work on the Edge Legacy WebAssembly behavior. More test would be needed i imagine. Server-side on the other hand is often just "action" transfert more than manipulating complex API behaviors.

Is there high demand for Edge Legacy support ?

**Comment by benmiller86** [comment]
@Daddoon edge legacy is about as popular as IE11 amount our userbase

**Comment by Daddoon** [comment]
@benmiller86 WASM or Server-Side Blazor ?

**Comment by benmiller86** [comment]
@Daddoon we are using server side. Am I right in thinking Blazor WASM is simply not possible on IE 11 even with polyfills etc?

I just want to thank you for your support on this. We pay for suppliers with SLAs that are far less responsive that you have been!

**Comment by Daddoon** [comment]
@benmiller86 In all cases, WASM will not be possible on IE11. But maybe it will be possible on Legacy Edge, but it's something harder to evaluate, as i don't know if the breaking changes in .NET 5 for WASM are on the WebAssembly side or the Javascript API side of Blazor.

I have opened an issue here https://github.com/Daddoon/Blazor.Polyfill/issues/39 for following Legacy Edge support in Server-Side.
I don't think there is a lot of things to change, but the main problem will be to find or create a kind of Windows 10 VM with the Legacy Edge installed instead of the Chromium one, in order to do some testing.

**Comment by benm-eras** [comment]
@Daddoon I don't know if you have access to one, but my MSDN subscription provides access to ISO files **all** versions of Windows 10 back to 1511. Also Azure has images for "Windows 10 Enterprise 2016 LTSB" and 1809 which should have legacy Edge.

Regarding IE11 and WASM, that is what I expected, and was actually the reason we're using server over WASM. 

I have confirmed that your recent changes do indeed work in IE11. Thank you again!

**Comment by Daddoon** [comment]
Thanks for your feedback for IE11 !

I will continue the discussion in this https://github.com/Daddoon/Blazor.Polyfill/issues/39 issue instead, in order to avoid to spam other suscribed users to this issue.

**Comment by Daddoon** [comment]
Even if the issue is closed, as an other update has been released, i post the same message here for the ones who subscribed:

Update shipped !

- Nuget page: https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.100.1
- Some additional informations on the updated doc: https://github.com/Daddoon/Blazor.Polyfill
- Release page here: https://github.com/Daddoon/Blazor.Polyfill/releases/tag/5.0.100.1

> - Add **Edge Legacy** (EdgeHTML engine) support
> - Fix missing reconnection modal behavior on **Internet Explorer 11** and **Edge Legacy**
> - Add pre-caching of all files needed for this library at the first web app request, in order to prevent further requests to wait for file generation on the server before serving the app. This mean that, now, if the app page is shown, then everything is ready.

Closing the issue !
