### ISSUE TITLE
InputFile

### ISSUE THREAD

**Issue by rjwii** [Daddoon/Blazor.Polyfill#51]
There appears to be an issue when uploading files using the <InputFile> tag. The upload works fine in Chrome, but fails in MSIE11. The reported error is:

Unhandled exception at line 8, column 69303 in http://<url>/_framework/blazor.server.js
0x800a1389 - JavaScript runtime error: Number expected

**Comment by Daddoon** [comment]
Are you talking about something at boot, or using file input functionality of the browser ?
Are you talking about this tag:

```html
<input type="file" />
```

**Comment by rjwii** [comment]
Sorry -- it looks like my comment had the markup taken out! I'm talking about using the Blazor [InputFile] component - https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0

**Comment by Daddoon** [comment]
Thanks for the report.
I do not have the time to look at it currently, but maybe at the end of the month.

However, you can surely workaround this (with some efforts) by doing some work manually about the file input native behavior in the browser.

I don't know yet if the error is due to some API missing that can be Polyfilled, or a feature that cannot be overriden.

**Comment by Daddoon** [comment]
Christmas before Christmas !
The updated NuGet package with the fix is available on Nuget and on the release page:

https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.100.4

Closing the issue !
