### ISSUE TITLE
Chrome & Firefox support...

### ISSUE THREAD

**Issue by raphadesa** [Daddoon/Blazor.Polyfill#54]
Hello, could you also please add Chrome & Firefox support as they also don't understand ES6, then your library would be just perfect !!! Many thanks, Raphaël

**Comment by Daddoon** [comment]
What do you mean by that ? Recent versions of Chrome and Firefox seems to support this from a long time.
Are you targeting a specific versions of theses Browsers ?

One possible update for the library would be to add a kind of "override" in the Server configuration for this lib, in order to force IE file serving behavior even if we are not running under IE.

Can you explain more about your issue ?

**Comment by raphadesa** [comment]
First of all thanks for your early reply.

My issue is the following : when using Chrome 65 or below (which is not so old as it was released on 2018), I'm facing this problem : when using a Blazor EditForm component, I can't submit a form, instead the page redirects to itself plus a question mark "?". I use the DataAnnotationValidator, a OnValidSubmit handler, and a button type="submit", very basic stuff. Have you had the opportunity to test that ? Do you know if it's something I can fix easily? I've already spent a lot of time in trying to solve this issue. 

Thanks very much for your help!

Best regards,

Raphaël

**Comment by Daddoon** [comment]
Cannot say anything as i don't have a look on your app behavior.
Do you have error in the browser console ?

Here is an updated version for you to test of the plugin, can you try to install it instead ?

[BlazorPolyfill.Server.5.0.100.5.zip](https://github.com/Daddoon/Blazor.Polyfill/files/5766065/BlazorPolyfill.Server.5.0.100.5.zip)

Just unzip the file and try to install the package manually.

In Startup.cs you should try to change one line by using this instead:

```csharp
app.UseBlazorPolyfill(true);
```
This flag will force to consider all required request as needing ES5 fallback.
Then go back to me to say if this resolve your issue.

If you have a repro project and/or specific versions of browser i can test in the meantime, it would be nice.

**Comment by raphadesa** [comment]
Hello,

Good news, it seems to do the trick !
Both Chrome 49 and Firefox 68 worked !
I think we push this fix on production tomorrow, I will let you know if we have any other issue.

Thank you very much for your support, and have a great day !

Raphaël

**Comment by Daddoon** [comment]
Good news !

It would be great to have your feedback, I will then merge and release an official update.

Are you planning to ship this on a regular web server or a Azure Web App ? 

There is a possible issue on Azure if using the Linux app container, as the default image is missing the good GLIBC version used for the V8 engine used to transpile the ES6 code to ES5 on the fly.

I have made a workaround by using ChakraCore engine instead in another branch, but cannot test it as I don’t have Azure accounts but it does fix the issue I had when testing with Debian 10 default image without any additional installation.

Keep me informed about this point if you are concerned.

**Comment by raphadesa** [comment]
Hello,

We use a regular web server.

For info, the package you sent me also works on old Safari for Mac.

I will provide a feedback on how the fix is working in the next days.

Best regards,

Raphaël

**Comment by Daddoon** [comment]
Just for information, i released an official update with the changes you asked, but also some changes like using ChakraCore engine as default engine, instead of V8 for transpilation as it had some issue as i said on some Linux images.

Also i have made changes to the impementations of the library options in order to be more futur proof and for readability.
So as i stated in the [Additional options](https://github.com/Daddoon/Blazor.Polyfill#additional-options) section of the documentation, use this syntax instead:

```csharp
app.UseBlazorPolyfill(
    (options) => {
        options.ForceES5Fallback = true;
    });
```

The new package is available here:

https://www.nuget.org/packages/BlazorPolyfill.Server/5.0.100.5
https://github.com/Daddoon/Blazor.Polyfill/releases/tag/5.0.100.5

And so the release notes:

> - Fix dependencies error on Linux (Debian 10 default installation)
> - Potentially fix Azure Web App error with the default Linux image container
> - Added BlazorPolyfillOptions parameter for UseBlazorPolyfill methods in order to configure additional behaviors at startup
> - Added the ForceES5Fallback option in order to force ES5 and Polyfill behaviors even if the browser is not Internet Explorer 11 or Edge Legacy.
> - Added ChakraCore engine image and set it as default. V8 engine is still present as fallback engine.

**Comment by Daddoon** [comment]
Also, as i don't know how if you have continuous integration (CI) or else for your production environment, as i named the final release with the same name as the manual package you had, if you do the update, be sure to clean any NuGet cache about this reference on your computers and build server.

Just to be sure that it does download the NuGet library reference from the official release and not from the version i given you manually.

Sorry for the inconvenience, i didn't thought about it before releasing.
Maybe this will not affect your build integration at all.

**Comment by Daddoon** [comment]
I will close this issue, as it seems to be ok for the given initial scenario, but feel free to comment or reopen if somehting go wrong.
