### ISSUE TITLE
JavaScript Isolation is not working in IE11 with .NET 5.0 Blazor Server Application

### ISSUE THREAD

**Issue by icsilambarasan** [Daddoon/Blazor.Polyfill#57]
Used latest polyfill 5.0.100.5

Blazor Server App - .NET 5.0

![image](https://user-images.githubusercontent.com/28433279/104718295-af00d680-5750-11eb-9d2f-484f3c44dc9a.png)

**Comment by Daddoon** [comment]
Please provide more informations.

- Version of the .NET SDK.
- You Startup.cs file content
- Your starting page content declaration.

The current Polyfill 5.0.100.5 has been tested against .NET SDK 5.0.100 actually.

**Comment by icsilambarasan** [comment]
@Daddoon 

Please find the below details.

- .NET SDK version - 5.0.100

**Startup.cs file content**
public void ConfigureServices(IServiceCollection services)
{
	services.AddRazorPages();
	services.AddServerSideBlazor();
	services.AddSingleton<WeatherForecastService>();
	services.AddBlazorPolyfill();
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}
	else
	{
		app.UseExceptionHandler("/Error");
		app.UseHsts();
	}

	app.UseHttpsRedirection();
	app.UseBlazorPolyfill();
	app.UseStaticFiles();            
	app.UseRouting();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapBlazorHub();
		endpoints.MapFallbackToPage("/_Host");
	});
}

**Replication code snippets**

- **_Host.cshtml**
<body>
    <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" />
    </app>

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.polyfill.min.js"></script>
    <script src="_framework/blazor.server.js"></script>
</body>

- **Counter.razor**
@page "/counter"

@inject IJSRuntime JSRuntime
@implements IAsyncDisposable
Enter your name:
<input @bind="name" />
<button @onclick="Submit">Submit</button>

@code {
    private string name;

    // Load the module and keep a reference to it
    // You need to use .AsTask() to convert the ValueTask to Task as it may be awaited multiple times
    private Task<IJSObjectReference> _module;
    private Task<IJSObjectReference> Module => _module ??= JSRuntime.InvokeAsync<IJSObjectReference>("import", "./js/counter.js").AsTask();

    async Task Submit()
    {
        var module = await Module;
        await module.InvokeVoidAsync("sayHi", name);
    }

    public async ValueTask DisposeAsync()
    {
        if (_module != null)
        {
            var module = await _module;
            await module.DisposeAsync();
        }
    }
}

- **wwwroot/js/counter.js**
export function sayHi(name) {
    alert("hello ${name}!");
}

Run the application with modified above changes and click the submit button.

**Comment by Daddoon** [comment]
Actually the problem is that IE11 is limited by ES5.
This mean that "import" / "require" and "module" functionnalities are not present natively.
That's also why "export" does not work too.

I think one possible solution would be to integrate some import fallback to unsupported browsers, like the ideas proposed here:
https://medium.com/@karimjavith/dynamic-module-loading-ie-11-edge-chrome-firefox-6d4f1842b1bf

But this also mean that we would have to use another keyword for the **IJSObjectReference** because **import** is reserved.

I can imagine something like the proposed solution in the article **$import** or something else like **import_compat**, **_import**, i don't know yet.

The method would then return do the right thing for each browser.

Still we will have some limitation on IE11 i have to dig.

JS Isolation, strictly speaking, would be missing on IE11, even with transpilation, but we could "simulate" the isolation if a Webpack version of your JS file is also built and choose dynamically for IE11 implementation at runtime. Babel would just have to transpile in the process.

An entrypoint would be generated for your JS library, that we would use internally to simulate the Module object behavior returned in Blazor. Then JS isolation will be respected.

We can dig some informations here:

https://stackoverflow.com/a/34361312/1417492

I don't know yet if it will be fast and easy to implement this, but if we want to make this "transparent" to the developement workflow, we would have to deal with Webpack and Babel on all your JS file modules at build time IF they were modified.

**Comment by Daddoon** [comment]
Hi @icsilambarasan !

Thanks for your issue, this was a good challenge to try !

I have shipped an update that workaround this issue, of course with some limitation or constraint to respect.

You just have to update your **BlazorPolyfill.Server** package to 5.0.100.6, and follow this documentation for implementing the thing in your project: https://github.com/Daddoon/Blazor.Polyfill/blob/master/README.md#optional-javascript-isolation--module-import-support .
