### ISSUE TITLE
Is it possible to cache _patchedBlazorServerFile in file system?

### ISSUE THREAD

**Issue by SpeednetGroup** [Daddoon/Blazor.Polyfill#80]
It looks like the transpiled version of blazor.server.js is stored in a private static variable, so every time the application restarts (for example, when the IIS app pool is restarted), the transpiled version of blazor.server.js has to be recreated using Babel.

That adds around 4-5 seconds to the app startup time, which for a high-volume production site can be a long time.

In reality, blazor.server.js gets updated infrequently, so if the transpiled version were cached in the file system, it would be very rare for that 4-5 second recreate time to be needed.

Maybe two files could be stored -- (1) the transpiled (and minified) version of blazor.server.js, and (2) a file just containing the hash of the original blazor.server.js, in order to detect when the source file has been changed.

What do you think?

**Comment by SpeednetGroup** [comment]
Another way to avoid long startup time might be to create the transpiled version asynchronously in a separate thread so that app startup does not hang until it's finished.

**Comment by Daddoon** [comment]
Indeed, you are right about the Hash thing.

And it's actually the root i have took if you use the ES5 dynamic transpilation additional functionnalities, where a "es5cache" folder is created by default.

BUT **blazor.server.js** has been excluded for this logic.
The main reason for this is because this file must me modified manually at startup.

Some because the used Babel version through React.NET is too old to manage some newer Regexp syntax and fail, so the fix must be done manually before transpiling. And there is some other manual fix i had to do, i don't remember exactly what as i don't have the code in front of me.

The more "versions friendly" implementation would be to keep a copy/hash copy of every blazor.server.js files in the library, and serve the "correct" fixes for specific file hashes, and also, do some kind of hash cache correspondance, like the es5cache functionnality.

For now, if you want to prevent any dynamic transpilation and fixes, you may try to use the **UsePackagedBlazorLibrary** option in **Startup.cs**:

```csharp
  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
  {
      /* Other method calls */
      app.UseBlazorPolyfill((options) =>
      {
          options.UsePackagedBlazorServerLibrary = true;
      });
  }
```

With this option set to true, it will not try to do any transpilation at startup. This option was initially done for system's than cannot do transpilation because of missing JS Engines libraries, like on ARM.

The advantage of using the transpiled versions was to have some kind of "automatic" changes and repair if the Microsoft library evolve, of course, with no guaranties that it will not break at some time (that's why updates are for in the end !).

In the end, you are right, at least a way to "detect" that the blazor.server.js file has been converted by comparing the source hash AND that the Blazor.Polyfill library is the same as before (avoiding to cache a breaked transpilation due to a new Blazor Server version, so taking a look on a new Blazor.Polyfill version too), and if everything is ok, make it cached !

I don't have the time window yet to take a look on that, but i will take a look next week.

**Comment by Daddoon** [comment]
> Another way to avoid long startup time might be to create the transpiled version asynchronously in a separate thread so that app startup does not hang until it's finished.

It was the first "strategy" a long time ago, but it could have some weirds effects if, IMO, not every file was ready at boot. And if i remember, i'm not sure if the transpilation process work from another thread.

I think the best bet was your first idea, that we manage a proper transpilation cache specifically for this file that must be managed/fixed differently. Then, except the first boot after a .NET/Blazor/Blazor.Polyfill update, everything would run smoothly anytime.

**Comment by SpeednetGroup** [comment]
Thanks Daddoon, obviously this is something you've spent a good deal of time considering previously.  I look forward to seeing what you come up with; in the meantime will experiment with the UsePackagedBlazorServerLibrary option you mentioned.  Thanks very much for the quick and detailed reply!

**Comment by Daddoon** [comment]
Thanks for your reply.

I will surely take a look, i did make a not on my calendar for that.
I just read again some doc information of my API, and a little detail is misleading obviously:

```csharp
// If None is selected, only the blazor.server.js file will be converted to ES5.
// This is the minimum requirement and goal of this library.
// ES5ConversionScope.None = 0,
```

This statement is at the same time true and false. I mean, yes, the blazor.server.js file is indeed converted to ES5, like RCL or other JS files if you change the enum value. But this is the only one that don't go directly and physically in cache actually because of the "fix" pipeline that is done differently.

So the next step is obviously make it work, at least apparently, like the others, meaning having a es5cache version manageable by the library (and so avoid the transpilation time issue).

**Comment by Daddoon** [comment]
Sorry, i'm not yet on the upgrade, i have some aditionnal work and request from my client, so have less spare time this week for this.
But this is still on my To do list.

**Comment by Daddoon** [comment]
Done here:

- [Nuget.org](https://www.nuget.org/packages/BlazorPolyfill.Server/6.0.200)
- [GitHub](https://github.com/Daddoon/Blazor.Polyfill/releases/tag/6.0.200.0)
