### ISSUE TITLE
Will it work on Blazor Client Side (WebAssembly)

### ISSUE THREAD

**Issue by smjltd** [Daddoon/Blazor.Polyfill#9]
I am using client side i desperately need to run my application on IE 11

**Comment by smjltd** [comment]
I tested on Blazor Client Side and Blazor Client Asp.Net Core Hosted.
Failed with 

`Unhandled promise rejection Error: Failed to start platform. Reason: Error: This browser does not support WebAssembly.`

**Comment by Daddoon** [comment]
You cannot use Blazor on Internet Explorer 11 with the **client-side** implementation. It was possible on first versions because Microsoft adopted an **asm.js** fallback, but this has been deprecated since **Blazor 0.7.0** or something like that.

The current implementation of Blazor only work with Browsers compatible with **WebAssembly**. As stated with the error you written, Internet Explorer 11 does not support WebAssembly, so you can't use the client-side version on Internet Explorer 11.

However, you **should be able to use server-side version** of Blazor. There is officially some issue to run it from Microsoft side, but this plugin workaround the missing parts.

If you need to make it work on both modern and old browsers, BUT you want to have a client-side version on all browsers (except IE11 of course), consider developping a client-side version of Blazor, create a server-side project that base it's code on the client-side implementation, and then deploy the server-side version on a server.

You may take a look at this strategy with the @Suchiman [BlazorDualMode](https://github.com/Suchiman/BlazorDualMode) demo sample.

The only difference i would make, will be to change:

	```js
	<script id="blazorMode"></script>
	<script>
		document.getElementById("blazorMode").src = window.location.search.includes("mode=server") ? "_framework/blazor.server.js" : "_framework/blazor.webassembly.js";
	</script>
	```

in the BlazorDualMode sample, to:

	```js
	<script id="blazorMode"></script>
	<script>
		document.getElementById("blazorMode").src = !window.hasOwnProperty("WebAssembly") ? "_framework/blazor.server.js" : "_framework/blazor.webassembly.js";
	</script>
	```
If WebAssembly global object is not found at startup, that mean that the browser don't support it, so your browser will fallback to the **blazor.server.js** implementation instead of the client-one.

Of course don't forget to add **blazor.polyfill.js** to your project, as even with server-side, IE11 has some issues that are fixed with this library, at startup.

Regards.

**Comment by smjltd** [comment]
For me unfortunately Server Side is not possible. as i am running a blazor application on SharePoint Pages as a Client.
 
Will update my repo on github soon, so every one can use and modify the code.

Thank You ❤️
